package ir.cafebazaar.bundlesigner;

public enum ReturnCodes {
    SUCCESS, TMP_CREATE_FAILURE, INVALID_PARAMS, MISSED_MIN_SDK, RUNTIME_EXCEPTION, INVALID_BUNDLE, BUNDLE_TOOL_EXCEPTION,
    MALFORMED_APK, TMP_DELETE_FAILURE;
}
